name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker build -t abhinavm945/deploy-reactjs-frontendapp .
          docker push abhinavm945/deploy-reactjs-frontendapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull abhinavm945/deploy-reactjs-frontendapp:latest
      - name: Stop and Remove Old Container
        run: |
          docker stop reactContainer || true
          docker rm reactContainer || true
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactContainer abhinavm945/deploy-reactjs-frontendapp:latest
